on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
name: Build Birthday CI

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests
      - name: execute py script
        run: |
          python main.py
        env:
          GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
          CALL_ME_BOT_URL: ${{ secrets.CALL_ME_BOT_URL }}
          CALL_ME_BOT_API_KEY: ${{ secrets.CALL_ME_BOT_API_KEY }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: api-responses
          path: ./callmebot.txt



